os: linux
dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    packages:
      - libboost-test-dev
script:
  - cmake .
  - cmake --build .
  - cmake --build . --target project_test
  - cmake --build . --target package
  - ls -ila
  - ls -ila test
deploy:
  provider: script
  skip_cleanup: true
  script:
    - curl -f -T matrix-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uilia64:$BINTRAY_KEY "https://api.bintray.com/content/ilia64/otus-cpp/matrix/$TRAVIS_BUILD_NUMBER/matrix-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
